### PR TITLE
Exclude files ending in .min.js from being browserified. (issue #45)

### PR DESCRIPTION
**Pull request by wmhilton**
I try to keep my pull requests small so they take less time to review. :wink:

### CODE REVIEW

**Comment by zeke** [comment]
Looks good to me.

Since this is using `String.prototype.endsWith()`, it should be noted that we're now only supporting node >=4. Can you add an `engines` stanza to package.json?

**Comment by wmhilton** [comment]
> Since this is using String.prototype.endsWith(), it should be noted that we're now only supporting node >=4.

How did you know that?? Is that knowledge in your brain or do you have some awesome linter tool that tells you these things?

**Comment by zeke** [comment]
> Is that knowledge in your brain

This particular bit, yes. :)

**Comment by zeke** [comment]
Looks good. Will cut a new release soon.

**Comment by zeke** [comment]
```
❯ np minor
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 jus 0.22.0 published 🎉
```

**Comment by zeke** [comment]
@wmhilton would you able to document this new feature in https://github.com/zeke/jus.js.org ?

**Comment by zeke** [comment]
> Is there any benefit for jus to exclude .min.css? (efficiency and time are good ones)

👍

**Comment by wmhilton** [comment]
Ah? I didn't realize jus was processing minified CSS files, but I see its got auto-prefixing magic! Um... I personally would be fine with excluding `.min.css`. On the other hand, I haven't personally experienced any slowdown from it like I have from the JS one.

**Pull request merged**
