### PR TITLE
Add jus server 404 error page

### LINKED ISSUE #37: Use `404`.html` if avilable for custom 404 page
Could do what GitHub Pages and Surge do: use a `404.html` file in the project root, if available.

### PR DESCRIPTION
**Pull request by elingerojo**
Closes #37

Note: It includes a TODO comment to remove fallback code if it feels appropriate . It could be done in any future revision.

error404

### CODE REVIEW

**Comment by zeke** [comment]
Nice!

**Comment by zeke** [comment]
```
❯ np minor
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 jus 0.23.0 published 🎉
```

**Comment by zeke** [comment]
Gracias, @elingerojo!

**Comment by elingerojo** [comment]
Yippee!

**Comment by wmhilton** [comment]
OMG that looks amazing!

**Pull request merged**
